# Generated by Django 3.0.7 on 2020-07-16 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0004_auto_20200716_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name="date de l'appel")),
                ('heure_d', models.TimeField()),
                ('heure_f', models.TimeField()),
                ('cursus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lycee.Cursus')),
            ],
        ),
        migrations.AddField(
            model_name='presence',
            name='appel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lycee.Appel'),
        ),
    ]
