# Generated by Django 3.0.7 on 2020-07-16 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0005_auto_20200716_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presence',
            old_name='date',
            new_name='date_presence',
        ),
    ]
