# Generated by Django 3.0.7 on 2020-07-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0007_auto_20200719_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appel',
            name='heure_d',
        ),
        migrations.RemoveField(
            model_name='appel',
            name='heure_f',
        ),
    ]
