# Generated by Django 3.0.7 on 2020-08-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0008_auto_20200719_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='appel',
            name='debut',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='appel',
            name='fin',
            field=models.TimeField(null=True),
        ),
    ]
